version: "3.7"

services:
  database_finapi:
    image: postgres
    container_name: default
    restart: always
    ports:
      - 5432:5432
      - 9229:9229
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
